
policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: false
      dco: false
      gpg: false
      spellcheck:
        locale: US
      maximumOfOneCommit: true
      conventional:
        types:
          - chore
          - docs
          - perf
          - refactor
          - style
          - test
          - build
        scopes:
          - policy
          - pipeline
