spring:
  datasource:
    url: jdbc:mysql://mysql:3306/mood_feed
    username: ${MYSQL_USER:moodfeed}
    password: ${MYSQL_PASSWORD:fake}
management:
  endpoints:
    web:
      cors:
        allowed-origins: http://mood-feed-backend-jx-staging.35.195.151.253.nip.io
