spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mood_feed
    username: root
    password: 123qweasd
    hikari:
      data-source-properties:
        serverTimezone: UTC
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml

server:
  port: 8080

management:
  endpoint:
    health:
      probes:
        enabled: true
