spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mood_feed
    username: moodfeed
    password: 123QWEasd
    hikari:
      data-source-properties:
        serverTimezone: UTC
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak.35.195.151.253.nip.io/auth/realms/mood-feed/protocol/openid-connect/certs

security:
  provider: keycloak
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:*}
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    exposed-headers: Authorization,content-type
    allowed-headers: Authorization,content-type

server:
  port: 8080
  compression:
    enabled: true
  servlet.session:
    # Session timeout after 1 minute. In case somehow sessions get still opened for stateless application.
    timeout: 120

management:
  server:
    port: 8081
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"

