
# generated by: jx gitops variables
export APP_NAME="mood-feed-backend"
export BRANCH_NAME="master"
export BUILD_NUMBER="25"
export DOCKERFILE_PATH="Dockerfile"
export DOCKER_REGISTRY="gcr.io"
export DOCKER_REGISTRY_ORG="sdlc-286111"
export JX_CHART_REPOSITORY="http://jenkins-x-chartmuseum:8080"
export PIPELINE_KIND="release"
export REPO_NAME="mood-feed-backend"
export REPO_OWNER="vitech-team"
