
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    exposer: Ingress
    domain: 35.224.13.149.nip.io
    http: true
    tlsacme: false

cleanup:
  Args:
    - --cleanup
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded

preview:
  image:
    repository:
    tag:
    pullPolicy: IfNotPresent
  livenessProbe:
    initialDelaySeconds: 120
  env:
    SPRING_PROFILES_ACTIVE: preview

mysql:
  mysqlPassword: 123QWEasd
  mysqlDatabase: moodfeed
  mysqlUser: moodfeed
  mysqlRootPassword: 123QWEasd
  initializationFiles:
    mood_feed_db.sql: |-
      CREATE DATABASE IF NOT EXISTS mood_feed DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
