environments:
  default:
    values:
      - jx-values.yaml
repositories:
  - name: stable
    url: https://charts.helm.sh/stable
releases:
  - chart: stable/mysql
    name: mysql
    version: 1.6.6
    namespace: '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
    values:
      - mysql-values.yaml
  - chart: '../charts/{{ requiredEnv "APP_NAME" }}'
    name: preview
    wait: true
    createNamespace: true
    namespace: '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
    values:
      - jx-values.yaml
      - imagePullSecrets.yaml
      - values.yaml.gotmpl
    hooks:
      - events: [ "presync" ]
        showlogs: true
        command: "jx"
        args:
          - secret
          - copy
          - --create-namespace
          - --selector
          - "secret.jenkins-x.io/replica-source=true"
          - --to
          - '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
