apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: jx-pullrequest
  labels:
    jenkins.io/pipelineType: build
    owner: vitech-team
spec:
  pipelineSpec:
    params:
      - description: the unique build number
        name: BUILD_ID
        type: string
        default: ""
      - description: the name of the job which is the trigger context name
        name: JOB_NAME
        type: string
      - description: the specification of the job
        name: JOB_SPEC
        type: string
      - description: 'the kind of job: postsubmit or presubmit'
        name: JOB_TYPE
        type: string
      - default: master
        description: the base git reference of the pull request
        name: PULL_BASE_REF
        type: string
      - description: the git sha of the base of the pull request
        name: PULL_BASE_SHA
        type: string
      - default: ""
        description: git pull request number
        name: PULL_NUMBER
        type: string
      - default: ""
        description: git pull request ref in the form 'refs/pull/$PULL_NUMBER/head'
        name: PULL_PULL_REF
        type: string
      - default: master
        description: git revision to checkout (branch, tag, sha, ref…)
        name: PULL_PULL_SHA
        type: string
      - description: git pull reference strings of base and latest in the form 'master:$PULL_BASE_SHA,$PULL_NUMBER:$PULL_PULL_SHA:refs/pull/$PULL_NUMBER/head'
        name: PULL_REFS
        type: string
      - description: git repository name
        name: REPO_NAME
        type: string
      - description: git repository owner (user or organisation)
        name: REPO_OWNER
        type: string
      - description: git url to clone
        name: REPO_URL
        type: string

    tasks:
      - name: fetch-repo
        taskRef:
          name: git-clone
        workspaces:
          - name: output
            workspace: shared-data

        params:
          - name: url
            value: $(params.REPO_URL)


  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi
  podTemplate:
    volumes:
      - name: podinfo
        downwardAPI:
          items:
            - fieldRef:
                fieldPath: metadata.labels
              path: labels
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
  serviceAccountName: tekton-build-bot
  timeout: 2h