apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  labels:
    branch: master
    build: "1"
    jenkins.io/pipelineType: build
    owner: jenkins-x-quickstarts
    repository: node-http
  name: jenkins-x-quickstarts-node-http-669qb-1
spec:
  pipelineSpec:
    params:
      - description: the unique build number
        name: BUILD_ID
        type: string
      - description: the name of the job which is the trigger context name
        name: JOB_NAME
        type: string
      - description: the specification of the job
        name: JOB_SPEC
        type: string
      - description: 'the kind of job: postsubmit or presubmit'
        name: JOB_TYPE
        type: string
      - default: master
        description: the base git reference of the pull request
        name: PULL_BASE_REF
        type: string
      - description: the git sha of the base of the pull request
        name: PULL_BASE_SHA
        type: string
      - default: ""
        description: git pull request number
        name: PULL_NUMBER
        type: string
      - default: ""
        description: git pull request ref in the form 'refs/pull/$PULL_NUMBER/head'
        name: PULL_PULL_REF
        type: string
      - default: master
        description: git revision to checkout (branch, tag, sha, ref…)
        name: PULL_PULL_SHA
        type: string
      - description: git pull reference strings of base and latest in the form 'master:$PULL_BASE_SHA,$PULL_NUMBER:$PULL_PULL_SHA:refs/pull/$PULL_NUMBER/head'
        name: PULL_REFS
        type: string
      - description: git repository name
        name: REPO_NAME
        type: string
      - description: git repository owner (user or organisation)
        name: REPO_OWNER
        type: string
      - description: git url to clone
        name: REPO_URL
        type: string
    tasks:
      - name: from-build-pack
        params:
          - name: BUILD_ID
            value: $(params.BUILD_ID)
          - name: JOB_NAME
            value: $(params.JOB_NAME)
          - name: JOB_SPEC
            value: $(params.JOB_SPEC)
          - name: JOB_TYPE
            value: $(params.JOB_TYPE)
          - name: PULL_BASE_REF
            value: $(params.PULL_BASE_REF)
          - name: PULL_BASE_SHA
            value: $(params.PULL_BASE_SHA)
          - name: PULL_NUMBER
            value: $(params.PULL_NUMBER)
          - name: PULL_PULL_REF
            value: $(params.PULL_PULL_REF)
          - name: PULL_PULL_SHA
            value: $(params.PULL_PULL_SHA)
          - name: PULL_REFS
            value: $(params.PULL_REFS)
          - name: REPO_NAME
            value: $(params.REPO_NAME)
          - name: REPO_OWNER
            value: $(params.REPO_OWNER)
          - name: REPO_URL
            value: $(params.REPO_URL)

        taskSpec:
          params:
            - description: git url to clone
              name: REPO_URL
              type: string
            - default: master
              description: git revision to checkout (branch, tag, sha, ref…)
              name: PULL_PULL_SHA
              type: string
            - default: source
              description: subdirectory inside of /workspace to clone the git repo
              name: subdirectory
              type: string
            - description: the unique build number
              name: BUILD_ID
              type: string
            - description: the name of the job which is the trigger context name
              name: JOB_NAME
              type: string
            - description: the specification of the job
              name: JOB_SPEC
              type: string
            - description: 'the kind of job: postsubmit or presubmit'
              name: JOB_TYPE
              type: string
            - default: master
              description: the base git reference of the pull request
              name: PULL_BASE_REF
              type: string
            - description: the git sha of the base of the pull request
              name: PULL_BASE_SHA
              type: string
            - default: ""
              description: git pull request number
              name: PULL_NUMBER
              type: string
            - default: ""
              description: git pull request ref in the form 'refs/pull/$PULL_NUMBER/head'
              name: PULL_PULL_REF
              type: string
            - description: git pull reference strings of base and latest in the form 'master:$PULL_BASE_SHA,$PULL_NUMBER:$PULL_PULL_SHA:refs/pull/$PULL_NUMBER/head'
              name: PULL_REFS
              type: string
            - description: git repository name
              name: REPO_NAME
              type: string
            - description: git repository owner (user or organisation)
              name: REPO_OWNER
              type: string
            - name: USER_ID
              description: The user ID of the builder image user.
              default: "1000"
            - name: GROUP_ID
              description: The group ID of the builder image user.
              default: "1000"
          stepTemplate:
            env:
              - name: CNB_PLATFORM_API
                value: "0.3"
              - name: BUILD_ID
                value: $(params.BUILD_ID)
              - name: JOB_NAME
                value: $(params.JOB_NAME)
              - name: JOB_SPEC
                value: $(params.JOB_SPEC)
              - name: JOB_TYPE
                value: $(params.JOB_TYPE)
              - name: PULL_BASE_REF
                value: $(params.PULL_BASE_REF)
              - name: PULL_BASE_SHA
                value: $(params.PULL_BASE_SHA)
              - name: PULL_NUMBER
                value: $(params.PULL_NUMBER)
              - name: PULL_PULL_REF
                value: $(params.PULL_PULL_REF)
              - name: PULL_PULL_SHA
                value: $(params.PULL_PULL_SHA)
              - name: PULL_REFS
                value: $(params.PULL_REFS)
              - name: REPO_NAME
                value: $(params.REPO_NAME)
              - name: REPO_OWNER
                value: $(params.REPO_OWNER)
              - name: REPO_URL
                value: $(params.REPO_URL)
            name: ""
            resources:
              requests:
                cpu: 400m
                memory: 512Mi
            volumeMounts:
              - mountPath: /home/jenkins
                name: workspace-volume
              - mountPath: /home/jenkins/.gnupg
                name: volume-0
              - mountPath: /etc/podinfo
                name: podinfo
                readOnly: true
            workingDir: /workspace/source
          steps:
            - args:
                - -c
                - 'mkdir -p $HOME; git config --global --add user.name $GIT_AUTHOR_NAME; git config --global --add user.email $GIT_AUTHOR_EMAIL; git config --global credential.helper store; git clone $(params.REPO_URL) $(params.subdirectory); echo cloned url: $(params.REPO_URL) to dir: $(params.subdirectory); cd $(params.subdirectory); git checkout $(params.PULL_PULL_SHA); echo checked out revision: $(params.PULL_PULL_SHA) to dir: $(params.subdirectory)'
              command:
                - /bin/sh
              image: gcr.io/jenkinsxio/builder-jx:2.1.32-662
              name: git-clone

              workingDir: /workspace
            - args:
                - gitops
                - git
                - setup
                - --namespace
                - jx-git-operator
              command:
                - jx
              image: gcr.io/jenkinsxio/jx-cli:latest
              name: git-setup

              workingDir: /workspace
            - args:
                - '[ -d /builder/home ] || mkdir -p /builder && ln -s /tekton/home /builder/home'
              command:
                - /bin/sh
                - -c
              env:
                - name: _JAVA_OPTIONS
                  value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
              image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
              name: setup-builder-home

            - args:
                - step
                - git
                - merge
                - --verbose
                - --baseSHA
                - $(params.PULL_BASE_SHA)
                - --sha
                - $(params.PULL_PULL_SHA)
                - --baseBranch
                - $(params.PULL_BASE_REF)
              command:
                - jx
              env:
                - name: _JAVA_OPTIONS
                  value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
              image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
              name: git-merge

            - args:
                - gitops
                - variables
              command:
                - jx
              image: gcr.io/jenkinsxio/jx-cli:latest
              name: jx-variables

            - name: prepare2
              image: gcr.io/jenkinsxio/jx-cli:latest
              script: |
                #!/usr/bin/env bash
                echo "USER $(params.USER_ID):$(params.GROUP_ID)"
                chown -R "$(params.USER_ID):$(params.GROUP_ID)" "/tekton/home"
                chown -R "$(params.USER_ID):$(params.GROUP_ID)" "/workspace/source/"
                ls -la /tekton/home
                ls /tekton/home/.docker
                cat /tekton/home/.docker/config.json
                source /workspace/source/.jx/variables.sh
                export OUTPUT_IMAGE=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$BUILD_ID
                echo "$OUTPUT_IMAGE" >> /workspace/source/image.name
                cat /workspace/source/image.name
              securityContext:
                privileged: true
            - name: prepare
              image: alpine
              imagePullPolicy: Always
              command: [ "/bin/sh" ]
              args:
                - "-c"
                - |-
                  chown -R "$(params.USER_ID):$(params.GROUP_ID)" "/tekton/home" &&
                  chown -R "$(params.USER_ID):$(params.GROUP_ID)" "/layers" &&
                  chown -R "$(params.USER_ID):$(params.GROUP_ID)" "/cache" &&
                  chown -R "$(params.USER_ID):$(params.GROUP_ID)" "/workspace/source"
              securityContext:
                privileged: true
              volumeMounts:
                - name: layers-dir
                  mountPath: /layers
                - name: empty-dir
                  mountPath: /cache

            - name: build-container-buildpacks
              image: paketobuildpacks/builder:base
              script: |
                #!/usr/bin/env bash
                source /workspace/source/.jx/variables.sh

                export OUTPUT_IMAGE=$DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$BUILD_ID

                echo "Building next image: $DOCKER_REGISTRY/$DOCKER_REGISTRY_ORG/$APP_NAME:$BUILD_ID"
                /cnb/lifecycle/creator -app=/workspace/source \
                  -gid=$(params.GROUP_ID) \
                  -uid=$(params.USER_ID) \
                  -cache-dir=/cache \
                  -layers=/layers \
                  -platform=/platform \
                  $OUTPUT_IMAGE
              volumeMounts:
                - name: layers-dir
                  mountPath: /layers
                - name: empty-dir
                  mountPath: /cache
                - name: empty-dir
                  mountPath: /platform


            - args:
                - source /workspace/source/.jx/variables.sh && jx preview create
              command:
                - /bin/bash
                - -c
              env:
                - name: _JAVA_OPTIONS
                  value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
              image: gcr.io/jenkinsxio/jx-cli:latest
              name: promote-jx-preview

          volumes:
            - name: volume-0
              secret:
                secretName: jenkins-release-gpg
            - emptyDir: { }
              name: workspace-volume
            - downwardAPI:
                items:
                  - fieldRef:
                      fieldPath: metadata.labels
                    path: labels
              name: podinfo
            - name: docker-socket
              hostPath:
                path: /var/run/docker.sock
                type: Socket
            - name: empty-dir
              emptyDir: { }
            - name: layers-dir
              emptyDir: { }
            - name: container-registry-auth
              secret:
                secretName: tekton-container-registry-auth
  podTemplate:
    ImagePullSecrets: null
    hostNetwork: false
    schedulerName: ""
  serviceAccountName: tekton-bot
  timeout: 1h