apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-build-bot
  namespace: jx
  annotations:
    iam.gke.io/gcp-service-account: mood-feed-tekton@sdlc-286111.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    gitops.jenkins-x.io/pipeline: namespaces
secrets:
  - name: docker-gcr-test
  - name: tekton-git
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-build-bot
  namespace: tekton-pipelines
  annotations:
    iam.gke.io/gcp-service-account: mood-feed-tekton@sdlc-286111.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    gitops.jenkins-x.io/pipeline: namespaces
secrets:
  - name: docker-gcr-test
  - name: tekton-git

